
language : python
sudo : false
cache : false
python :
    - "3.5"
    - "3.6"

install :
    - pip install -r requirements.txt
    - pip install .

matrix :
    include :
        - os : linux
          dist : trusty
          sudo : required
          python : 3.5
        - os : linux
          dist : trusty
          sudo : required
          python : 3.6

script : py.test
